# Generated by Django 5.1.5 on 2025-02-11 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookmodel_review_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='choice_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.bookmodel'),
        ),
    ]
