# Generated by Django 5.1.5 on 2025-02-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_review_choice_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='choice_show',
            new_name='choice_books',
        ),
    ]
