    # Generated by Django 5.1.5 on 2025-02-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clothes',
            new_name='clothess',
        ),
    ]
